"use client";

import { ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { StaffRole } from "@/lib/authz";

type Person = { uid?: string; email: string; name?: string; role: StaffRole; department: string; status?: string };
const roleNames: Record<StaffRole, string> = { employee: "General employee", "department-manager": "Department manager", owner: "Owner", admin: "Admin" };

export function UserAccessManager() {
  const [users, setUsers] = useState<Person[]>([]), [invites, setInvites] = useState<Person[]>([]);
  const [email, setEmail] = useState(""), [role, setRole] = useState<StaffRole>("employee"), [loading, setLoading] = useState(true), [message, setMessage] = useState<string | null>(null);
  async function load() { setLoading(true); try { const response = await fetch("/api/access/users"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setUsers(data.users ?? []); setInvites(data.invites ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load staff access."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function invite(event: React.FormEvent) { event.preventDefault(); setMessage(null); const response = await fetch("/api/access/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, role, department: "operations" }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error ?? "Unable to save invitation."); setEmail(""); setMessage("Access saved. Send them to Fairway to request their secure email sign-in link."); void load(); }
  return <section className="access-manager"><header className="operations-hero"><div><div className="eyebrow">Firebase access control</div><h2>Users & permissions</h2><p>Invite feedback users, then control their operational reach by role.</p></div><div className="connection-badge"><span />Protected</div></header><div className="access-grid"><article className="detail-card"><div><div className="eyebrow">Invite staff</div><h3>Grant access</h3><p>Invited users receive a passwordless email sign-in link—no shared passwords.</p></div><form className="access-form" onSubmit={invite}><input aria-label="Staff email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" required type="email" /><select aria-label="Role" value={role} onChange={(event) => setRole(event.target.value as StaffRole)}>{Object.entries(roleNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><button className="button" type="submit"><UserPlus size={16} />Invite user</button></form>{message ? <p className="security-note">{message}</p> : null}</article><article className="detail-card"><div><div className="eyebrow">Role policy</div><h3>What each role can do</h3></div><ul className="permission-list"><li><strong>Employee</strong><span>Member lookup and approved messaging</span></li><li><strong>Department manager</strong><span>Team KPIs for their area</span></li><li><strong>Owner</strong><span>All reporting and workflow control</span></li><li><strong>Admin</strong><span>Users, settings, and all operational data</span></li></ul></article></div><section className="detail-card access-list"><div><div className="eyebrow">Directory</div><h3><UsersRound size={17} /> Active & invited users</h3></div>{loading ? <p>Loading access records…</p> : <div>{users.map((person) => <p key={person.uid}><strong>{person.name || person.email}</strong><span>{person.email} · {roleNames[person.role]} · active</span></p>)}{invites.map((person) => <p key={person.email}><strong>{person.email}</strong><span>{roleNames[person.role]} · invited, awaiting first sign-in</span></p>)}{!users.length && !invites.length ? <p>No staff users yet. Your bootstrap admin is created when that email link is used.</p> : null}</div>}</section></section>;
}
